Repository front-end-by-rimantas/19-grupe-portfolio-new-per, pull requests merged in 2020-12, with the labels that each got.

#53 Title style
  css/components/skills.css
  css/home-page.css
  index.html
Labels: css, fonts, html

#43 Header section
  css/components/hero.css
  css/home-page.css
  index.html
  package.json
Labels: help wanted

#51 Button styling
  css/components/button.css
Labels: css, css.animation, known bug, testing needed

#56 About
  css/components/about-me.css
  css/home-page.css
  index.html
Labels: need approve

#57 Client counter section design
  css/components/client-counter.css
  index.html
Labels: need approve

#93 responsive tablet/phone
  css/components/client-counter.css
  index.html
Labels: css.responsive, testing needed

#98 Portfolio section
  css/components/portfolio.css
  index.html
Labels: need approve

#100 Navigation style update
  css/components/navigation-bar.css
  index.html
Labels: css, testing needed

#95 Blog section design
  css/components/blog.css
  index.html
Labels: need approve

#106 Responsive about section
  css/components/about-me.css
  index.html
Labels: need approve

#108 Navigation bar link scrolls
  index.html
Labels: need approve

#111 Hero section responsive design
  css/components/hero.css
  index.html
Labels: css.responsive

#109 Blog section responsive design
  css/components/blog.css
  index.html
Labels: need approve

#117 Rendered client counter section
  index.html
  js/components/clientCounter/isValidClientCounterItem.js
  js/components/clientCounter/isValidInput.js
  js/components/clientCounter/renderClientCounter.js
  js/data/clientCounterData.js
  js/main-home.js
Labels: need approve

#136 Responsive testimonials
  css/components/client-counter.css
  css/components/testimonials.css
  index.html
Labels: need approve

#144 Portfolio section
  css/components/portfolio.css
  index.html
Labels: need approve

#145 Portfolio animation
  css/components/portfolio.css
  index.html
Labels: need approve, testing needed

#154 Main validation file and some validation update in client counter component
  js/components/clientCounter/isValidClientCounterItem.js
  js/components/clientCounter/isValidInput.js
  js/components/validator/Validator.js
Labels: need approve

#142 Counter numbers animation
  js/components/clientCounter/counterAnimation.js
  js/components/clientCounter/counterAnimationOnScroll.js
  js/components/clientCounter/renderClientCounter.js
  js/main-home.js
Labels: need approve

#157 gitignore file update
  .gitignore
Labels: high priority, need approve

#159 Hamburger CSS & JS
  css/components/layout.css
  css/components/mobile-nav.css
  css/components/navigation-bar.css
  css/home-page.css
  js/components/navigation/renderNav.js
Labels: css, javascript, testing needed

#160 Validation update
  js/components/heroIcons/isValidHeroIconInput.js
  js/components/heroIcons/isValidHeroIconItem.js
  js/components/myServices/areServicesValid.js
  js/components/myServices/isValidInput.js
  js/components/mySkills/areSkillsValid.js
  js/components/mySkills/isSkillsInputValid.js
  js/components/navigation/renderNav.js
  js/components/testimonials/Testimonials.js
  js/components/validator/Validator.js
Labels: need approve

#164 Filename changes
  js/components/navigation/RenderNav.js
  js/components/renderTypewriter/RenderTypewriter.js
Labels: bug, high priority

#167 Counter animation fix
  js/components/clientCounter/counterAnimation.js
  js/components/clientCounter/counterAnimationOnScroll.js
Labels: need approve
